/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritances;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class RestaurantTest {

    @Test
    public void testGetName() {
        Restaurant restaurant = new Restaurant("KFC", 4, "21$");
        assertEquals("KFC",  restaurant.getName());
    }
    @Test
    public void testGetStars() {
        Restaurant restaurant = new Restaurant("KFC", 4, "21$");
        assertEquals(4,  restaurant.getStars());
    }
    @Test
    public void testGetPrice() {
        Restaurant restaurant = new Restaurant("KFC", 4, "21$");
        assertEquals("21$",  restaurant.getPrice());
    }



    @Test
    public void testSetBody() {
       Review feedBack = new Review("KFC", "4", 2);
        feedBack.setBody("Mac");
        assertEquals("Mac",  feedBack.getBody());
    }
    @Test
    public void testGetAuthor() {
       Review feedBack = new Review("khaled","it was perfect" , 5);

        assertEquals("khaled",  feedBack.getAuthor());
    }

    @Test
    public void testAddReview() {
        Restaurant restaurant = new Restaurant("KFC", 4, "21$");
        restaurant.addReview("it was perfect", "khaled", 5);
        assertEquals("khaled says it was perfect so the 5* stars it is what they expect",restaurant.getReviews().get(0).toString());

    }

    @Test
    public void testToString() {
        Review pizzaHouse = new Review("mick", "I think i will never come again", 0);
        assertEquals("mick says I think i will never come again so the 0* stars it is what they expect", pizzaHouse.toString());
    }
}
