/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void testRoll() {
        int num = 5;
        int[] newArr = Main.roll(num);
        assertEquals(newArr.length, num);
    }

    @Test public void testContainsDuplicatesTrue(){
        int[] testArr = {10, 45, 45, 51, 52};
        assertTrue(Main.containsDuplicates(testArr));
    }

    @Test public void testCalculateAverages(){
        int[] testArr = {4, 5, 4, 7, 11};
        int result = 6;
        assertEquals(result, Main.calculateAverages(testArr));
    }

    @Test public void testArrayOfArraysLowestAverage() {
        int[][] testArr = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        int[] correctResponse = {55, 54, 60, 53, 59, 57, 61};
        assertArrayEquals(correctResponse, Main.arrayOfArraysLowestAverage(testArr));
    }


}
