/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.Scanner;
public class App {
    public static int gatesCheck(String path) {
        Scanner gates;
        int Errors = 0;
        int line = 0;
        try {
            gates = new Scanner(new BufferedReader(new FileReader(path)));

            while (gates.hasNextLine()){
                line++;
                String lineGates = gates.nextLine();
                if (lineGates.length()>0 && !(lineGates.endsWith(";") || lineGates.endsWith("{") || lineGates.endsWith("}") || lineGates.contains("if") || lineGates.contains("else"))){
                    Errors++;
                    System.out.println("Line:" + line + ":Missing semicolon.");
                }
            }
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
        System.out.println("Line " + Errors);
        return Errors;
    }
    public static void main(String[] args) {
        gatesCheck("./src/main/resources/gates.js");
    }
}
