/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test public void testManyErrors() {
        assertEquals(App.gatesCheck("./src/main/resources/ManyErrors.js"), 4);
    }
    @Test public void testGates() {
        assertEquals(App.gatesCheck("./src/main/resources/gates.js"), 46);
    }

    @Test public void testEmpty() {
        assertEquals(App.gatesCheck("./src/main/resources/empty.js"), 0);
    }

    @Test public void testFewErrors() {
        assertEquals(App.gatesCheck("./src/main/resources/fewErrors.js"), 2);
    }

    @Test public void testNoErrors() {
        assertEquals(App.gatesCheck("./src/main/resources/noErrors.js"), 0);
    }

    @Test public void testOneError() {
        assertEquals(App.gatesCheck("./src/main/resources/oneError.js"), 1);
    }
}
